COLUMNS = [
    'class',
    'type/scale',
    'name',
    'relevance',
    'text',
    'help',
    'language',
    'validaton',
    'mandatory',
    'other',
    'default',
    'same_default',
    'allowed_filetypes',
    'alphasort',
    'answer_width',
    'array_filter',
    'array_filter_exclude',
    'assessment_value',
    'category_separator',
    'display_columns',
    'display_rows',
    'dropdown_dates_year_min',
    'dropdown_dates',
    'dropdown_dates_year_max',
    'dropdown_prefix',
    'dropdown_prepostfix',
    'dropdown_separators',
    'dropdown_size',
    'dualscale_headerA',
    'dualscale_headerB',
    'em_validation_q_tip',
    'em_validation_q',
    'em_validation_sq',
    'em_validation_sq_tip',
    'equals_num_value',
    'exclude_all_others',
    'exclude_all_others_auto',
    'hidden',
    'hide_tip',
    'input_boxes',
    'location_city',
    'location_country',
    'location_defaultcoordinates',
    'location_mapheight',
    'location_mapservice',
    'location_mapwidth',
    'location_mapzoom',
    'location_nodefaultfromip',
    'location_postal',
    'location_state',
    'max_answers',
    'max_filesize',
    'max_num_of_files',
    'max_num_value',
    'max_num_value_n',
    'maximum_chars',
    'min_answers',
    'min_num_of_files',
    'min_num_value',
    'min_num_value_n',
    'multiflexible_checkbox',
    'multiflexible_max',
    'multiflexible_min',
    'multiflexible_step',
    'num_value_int_only',
    'numbers_only',
    'other_comment_mandatory',
    'other_numbers_only',
    'other_replace_text',
    'page_break',
    'prefix',
    'public_statistics',
    'random_group',
    'random_order',
    'reverse',
    'scale_export',
    'show_comment',
    'show_grand_total',
    'show_title',
    'show_totals',
    'slider_accuracy',
    'slider_default',
    'slider_layout',
    'slider_max',
    'slider_middlestart',
    'slider_min',
    'slider_rating',
    'slider_separator',
    'slider_showminmax',
    'suffix',
    'text_input_width',
    'time_limit_action',
    'time_limit_countdown_message',
    'time_limit_disable_next',
    'time_limit_disable_prev',
    'time_limit_message',
    'time_limit_message_delay',
    'time_limit_message_style',
    'time_limit_timer_style',
    'time_limit_warning_2_display_time',
    'time_limit_warning_2_message',
    'time_limit_warning_2_style',
    'time_limit_warning_2',
    'time_limit_warning',
    'time_limit',
    'time_limit_warning_display_time',
    'time_limit_warning_message',
    'time_limit_warning_style',
    'use_dropdown'
]

GLOBAL_SETTINGS = [
    ('S', '', 'sid', '', '561617'),
    ('S', '', 'owner_id', '', '1'),
    ('S', '', 'admin', '', 'LimeSurvey Development Team'),
    ('S', '', 'active', '', 'N'),
    ('S', '', 'anonymized', '', 'N'),
    ('S', '', 'format', '', 'G'),
    ('S', '', 'savetimings', '', 'N'),
    ('S', '', 'template', '', 'default'),
    ('S', '', 'language', '', 'en'),
    ('S', '', 'datestamp', '', 'Y'),
    ('S', '', 'usecookie', '', 'N'),
    ('S', '', 'allowregister', '', 'N'),
    ('S', '', 'allowsave', '', 'Y'),
    ('S', '', 'autonumber_start', '', '0'),
    ('S', '', 'autoredirect', '', 'N'),
    ('S', '', 'allowprev', '', 'Y'),
    ('S', '', 'printanswers', '', 'Y'),
    ('S', '', 'ipaddr', '', 'N'),
    ('S', '', 'refurl', '', 'N'),
    ('S', '', 'datecreated', '', '2012-04-04'),
    ('S', '', 'publicstatistics', '', 'Y'),
    ('S', '', 'publicgraphs', '', 'N'),
    ('S', '', 'listpublic', '', 'Y'),
    ('S', '', 'htmlemail', '', 'Y'),
    ('S', '', 'sendconfirmation', '', 'Y'),
    ('S', '', 'tokenanswerspersistence', '', 'N'),
    ('S', '', 'assessments', '', 'N'),
    ('S', '', 'usecaptcha', '', 'N'),
    ('S', '', 'usetokens', '', 'N'),
    ('S', '', 'attributedescriptions', '', 'a:3:{s:11:"attribute_1";a:3:{s:11:"description";s:11:"Attribute 1";s:9:"mandatory";s:1:"N";s:13:"show_register";s:1:"N";}s:11:"attribute_2";a:3:{s:11:"description";s:11:"Attribute 2";s:9:"mandatory";s:1:"N";s:13:"show_register";s:1:"N";}s:11:"attribute_3";a:3:{s:11:"description";s:11:"Attribute 3";s:9:"mandatory";s:1:"N";s:13:"show_register";s:1:"N";}}'),
    ('S', '', 'tokenlength', '', '15'),
    ('S', '', 'showxquestions', '', 'Y'),
    ('S', '', 'showgroupinfo', '', 'B'),
    ('S', '', 'shownoanswer', '', 'Y'),
    ('S', '', 'showqnumcode', '', 'X'),
    ('S', '', 'bouncetime', '', '0'),
    ('S', '', 'bounceprocessing', '', 'N'),
    ('S', '', 'showwelcome', '', 'Y'),
    ('S', '', 'showprogress', '', 'Y'),
    ('S', '', 'allowjumps', '', 'N'),
    ('S', '', 'navigationdelay', '', '0'),
    ('S', '', 'nokeyboard', '', 'N'),
    ('S', '', 'alloweditaftercompletion', '', 'N'),
    ('S', '', 'googleanalyticsstyle', '', '0'),
]

EN_SETTINGS= [
    ('SL', '', 'surveyls_title', '', 'Platforms Consultation', '', 'en'),
    ('SL', '', 'surveyls_description', '', 'Regulatory environment for platforms, online intermediaries, data and cloud computing and the collaborative economy', '', 'en'),
    ('SL', '', 'surveyls_welcometext', '', 'The views expressed in this public consultation document may not be interpreted as stating an official position of the European Commission. All definitions provided in this document by the European Commission are strictly for the purposes of this public consultation and are without prejudice to differing definitions the Commission may use under current or future EU law, including any revision of the definitions by the Commission concerning the same subject matters.', '', 'en'),
    ('SL', '', 'surveyls_email_invite_subj', '', 'Invitation to participate in a survey', '', 'en'),
    ('SL', '', 'surveyls_email_invite', '', 'Dear {FIRSTNAME},<br /> <br /> you have been invited to participate in a survey.<br /> <br /> The survey is titled:<br /> "{SURVEYNAME}"<br /> <br /> "{SURVEYDESCRIPTION}"<br /> <br /> To participate, please click on the link below.<br /> <br /> Sincerely,<br /> <br /> {ADMINNAME} ({ADMINEMAIL})<br /> <br /> ----------------------------------------------<br /> Click here to do the survey:<br /> {SURVEYURL}<br /> <br /> If you do not want to participate in this survey and don\'t want to receive any more invitations please click the following link:<br /> {OPTOUTURL}<br /> <br /> If you are blacklisted but want to participate in this survey and want to receive invitations please click the following link:<br /> {OPTINURL}', '', 'en'),
    ('SL', '', 'surveyls_email_remind_subj', '', 'Reminder to participate in a survey', '', 'en'),
    ('SL', '', 'surveyls_email_remind', '', 'Dear {FIRSTNAME},<br /> <br /> Recently we invited you to participate in a survey.<br /> <br /> We note that you have not yet completed the survey, and wish to remind you that the survey is still available should you wish to take part.<br /> <br /> The survey is titled:<br /> "{SURVEYNAME}"<br /> <br /> "{SURVEYDESCRIPTION}"<br /> <br /> To participate, please click on the link below.<br /> <br /> Sincerely,<br /> <br /> {ADMINNAME} ({ADMINEMAIL})<br /> <br /> ----------------------------------------------<br /> Click here to do the survey:<br /> {SURVEYURL}<br /> <br /> If you do not want to participate in this survey and don\'t want to receive any more invitations please click the following link:<br /> {OPTOUTURL}', '', 'en'),
    ('SL', '', 'surveyls_email_register_subj', '', 'Survey registration confirmation', '', 'en'),
    ('SL', '', 'surveyls_email_register', '', 'Dear {FIRSTNAME},<br /> <br /> You, or someone using your email address, have registered to participate in an online survey titled {SURVEYNAME}.<br /> <br /> To complete this survey, click on the following URL:<br /> <br /> {SURVEYURL}<br /> <br /> If you have any questions about this survey, or if you did not register to participate and believe this email is in error, please contact {ADMINNAME} at {ADMINEMAIL}.', '', 'en'),
    ('SL', '', 'surveyls_email_confirm_subj', '', 'Confirmation of your participation in our survey', '', 'en'),
    ('SL', '', 'surveyls_email_confirm', '', 'Dear {FIRSTNAME},<br /> <br /> this email is to confirm that you have completed the survey titled {SURVEYNAME} and your response has been saved. Thank you for participating.<br /> <br /> If you have any further questions about this email, please contact {ADMINNAME} on {ADMINEMAIL}.<br /> <br /> Sincerely,<br /> <br /> {ADMINNAME}', '', 'en'),
    ('SL', '', 'surveyls_dateformat', '', '6', '', 'en'),
    ('SL', '', 'email_admin_notification_subj', '', 'Response submission for survey {SURVEYNAME}', '', 'en'),
    ('SL', '', 'email_admin_notification', '', 'Hello,<br /> <br /> A new response was submitted for your survey "{SURVEYNAME}".<br /> <br /> Click the following link to reload the survey:<br /> {RELOADURL}<br /> <br /> Click the following link to see the individual response:<br /> {VIEWRESPONSEURL}<br /> <br /> Click the following link to edit the individual response:<br /> {EDITRESPONSEURL}<br /> <br /> View statistics by clicking here:<br /> {STATISTICSURL}', '', 'en'),
    ('SL', '', 'email_admin_responses_subj', '', 'Response submission for survey {SURVEYNAME} with results', '', 'en'),
    ('SL', '', 'email_admin_responses', '', 'Hello,<br /> <br /> A new response was submitted for your survey "{SURVEYNAME}".<br /> <br /> Click the following link to reload the survey:<br /> {RELOADURL}<br /> <br /> Click the following link to see the individual response:<br /> {VIEWRESPONSEURL}<br /> <br /> Click the following link to edit the individual response:<br /> {EDITRESPONSEURL}<br /> <br /> View statistics by clicking here:<br /> {STATISTICSURL}<br /> <br /> <br /> The following answers were given by the participant:<br /> {ANSWERTABLE}', '', 'en'),
    ('SL', '', 'surveyls_numberformat', '', '0', '', 'en'),
]


HARD_COLUMNS = [
    ['Q', ':', 'afAMF', '1', '[:] Multi-Flex 1-10', '', 'en', '', '', 'N', '', '1', '', '', '', 'afSrcFilter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', 'maxSelect', '', '', '', '', '', 'minSelect', '', '', '', '', 'ceil(num2)', 'floor(num)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '0', 'sq1', '', 'First sub-question', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '0', 'sq2', '', 'Second sub-question', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '0', 'sq3', '', 'Third sub-question', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '0', 'sq4', '', 'Fourth sub-question', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '0', 'sq5', '', 'Fifth sub-question', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '1', '1', '1', 'Never', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '1', '2', '2', 'Sometimes', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ['SQ', '1', '3', '3', 'Always', '', 'en', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
]
